apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-catalog
  namespace: default
  labels:
    app: product-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-catalog
  template:
    metadata:
      labels:
        app: product-catalog
    spec:
      containers:
        - name: product-catalog
          image: ""
          ports:
            - containerPort: 8085
          