apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-order
  namespace: default
  labels:
    app: product-order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-order
  template:
    metadata:
      labels:
        app: product-order
    spec:
      containers:
        - name: product-order
          image: ""
          ports:
            - containerPort: 8089
          