apiVersion: v1
kind: Service
metadata:
  name: product-order
  namespace: default
spec:
  ports:
  - name: http
    port: 8089
    targetPort: 8089
    protocol: TCP
  selector:
    app: product-order
  type: LoadBalancer