apiVersion: v1
kind: Service
metadata:
  name: product-catalog
  namespace: default
spec:
  ports:
  - name: http
    port: 8085
    targetPort: 8085
    protocol: TCP
  selector:
    app: product-catalog
  type: LoadBalancer