/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.7.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.api;

import org.openapitools.model.Catalog;
import org.openapitools.model.CatalogCreate;
import org.openapitools.model.CatalogUpdate;
import org.openapitools.model.Error;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2024-07-16T16:55:02.035577+05:30[GMT+05:30]", comments = "Generator version: 7.7.0")
@Validated
 
//@Tag(name = "catalog", description = "the catalog API")
public interface CatalogApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * POST /catalog : Creates a Catalog
     * This operation creates a Catalog entity.
     *
     * @param catalog The Catalog to be created (required)
     * @return Created (status code 201)
     *         or Bad Request (status code 400)
     *         or Unauthorized (status code 401)
     *         or Forbidden (status code 403)
     *         or Method Not allowed (status code 405)
     *         or Conflict (status code 409)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "createCatalog",
        summary = "Creates a Catalog",
        description = "This operation creates a Catalog entity.",
        tags = { "catalog" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Created", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Catalog.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "401", description = "Unauthorized", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "403", description = "Forbidden", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "405", description = "Method Not allowed", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "409", description = "Conflict", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/createCatalog",
        produces = { "application/json;charset=utf-8" },
        consumes = { "application/json;charset=utf-8" }
    )
    
    default ResponseEntity<Catalog> createCatalog(
        @Parameter(name = "catalog", description = "The Catalog to be created", required = true) @Valid @RequestBody CatalogCreate catalog
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{\n" +
                            "    \"catalogType\": \"Product Catalog\",\n" +
                            "    \"lifecycleStatus\": \"Active\",\n" +
                            "    \"validFor\": {\n" +
                            "        \"startDateTime\": \"1985-04-12T23:20:50.52Z\",\n" +
                            "        \"endDateTime\": \"1985-04-12T23:20:50.52Z\"\n" +
                            "    },\n" +
                            "    \"@type\": \"CatalogType\",\n" +
                            "    \"description\": \"A comprehensive catalog of all available products.\",\n" +
                            "    \"relatedParty\": [\n" +
                            "        {\n" +
                            "            \"@referredType\": \"Organization\",\n" +
                            "            \"role\": \"Supplier\",\n" +
                            "            \"@baseType\": \"BaseType\",\n" +
                            "            \"@type\": \"RelatedPartyType\",\n" +
                            "            \"name\": \"Tech Supplies Co.\",\n" +
                            "            \"id\": \"RP101\",\n" +
                            "            \"href\": \"https://openapi-generator.tech/suppliers/tech-supplies\",\n" +
                            "            \"@schemaLocation\": \"https://openapi-generator.tech/schema\"\n" +
                            "        },\n" +
                            "        {\n" +
                            "            \"@referredType\": \"Organization\",\n" +
                            "            \"role\": \"Distributor\",\n" +
                            "            \"@baseType\": \"BaseType\",\n" +
                            "            \"@type\": \"RelatedPartyType\",\n" +
                            "            \"name\": \"Global Distributors Inc.\",\n" +
                            "            \"id\": \"RP102\",\n" +
                            "            \"href\": \"https://openapi-generator.tech/distributors/global-distributors\",\n" +
                            "            \"@schemaLocation\": \"https://openapi-generator.tech/schema\"\n" +
                            "        }\n" +
                            "    ],\n" +
                            "    \"version\": \"1.2\",\n" +
                            "    \"@baseType\": \"BaseType\",\n" +
                            "    \"lastUpdate\": \"2000-01-23T04:56:07.000+00:00\",\n" +
                            "    \"name\": \"Global Product Catalog\",\n" +
                            "    \"id\": \"C1001\",\n" +
                            "    \"href\": \"https://openapi-generator.tech/catalogs/global-product-catalog\",\n" +
                            "    \"category\": [\n" +
                            "        {\n" +
                            "            \"@referredType\": \"ProductCategoryRef\",\n" +
                            "            \"@baseType\": \"BaseType\",\n" +
                            "            \"@type\": \"CategoryType\",\n" +
                            "            \"name\": \"Electronics\",\n" +
                            "            \"id\": \"CAT101\",\n" +
                            "            \"href\": \"https://openapi-generator.tech/categories/electronics\",\n" +
                            "            \"@schemaLocation\": \"https://openapi-generator.tech/schema\",\n" +
                            "            \"version\": \"1.0\"\n" +
                            "        },\n" +
                            "        {\n" +
                            "            \"@referredType\": \"ProductCategoryRef\",\n" +
                            "            \"@baseType\": \"BaseType\",\n" +
                            "            \"@type\": \"CategoryType\",\n" +
                            "            \"name\": \"Home Appliances\",\n" +
                            "            \"id\": \"CAT102\",\n" +
                            "            \"href\": \"https://openapi-generator.tech/categories/home-appliances\",\n" +
                            "            \"@schemaLocation\": \"https://openapi-generator.tech/schema\",\n" +
                            "            \"version\": \"1.0\"\n" +
                            "        }\n" +
                            "    ],\n" +
                            "    \"@schemaLocation\": \"https://openapi-generator.tech/schema\"\n" +
                            "}\n";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"message\" : \"message\", \"referenceError\" : \"https://openapi-generator.tech\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"message\" : \"message\", \"referenceError\" : \"https://openapi-generator.tech\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"message\" : \"message\", \"referenceError\" : \"https://openapi-generator.tech\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"message\" : \"message\", \"referenceError\" : \"https://openapi-generator.tech\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"message\" : \"message\", \"referenceError\" : \"https://openapi-generator.tech\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"message\" : \"message\", \"referenceError\" : \"https://openapi-generator.tech\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.CREATED);

    }


    /**
     * DELETE /catalog/{id} : Deletes a Catalog
     * This operation deletes a Catalog entity.
     *
     * @param id Identifier of the Catalog (required)
     * @return Deleted (status code 204)
     *         or Bad Request (status code 400)
     *         or Unauthorized (status code 401)
     *         or Forbidden (status code 403)
     *         or Not Found (status code 404)
     *         or Method Not allowed (status code 405)
     *         or Conflict (status code 409)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "deleteCatalog",
        summary = "Deletes a Catalog",
        description = "This operation deletes a Catalog entity.",
        tags = { "catalog" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Deleted"),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "401", description = "Unauthorized", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "403", description = "Forbidden", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "405", description = "Method Not allowed", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "409", description = "Conflict", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/deleteCatalog/{id}",
        produces = { "application/json;charset=utf-8" }
    )
    
    default ResponseEntity<Void> deleteCatalog(
        @Parameter(name = "id", description = "Identifier of the Catalog", required = true, in = ParameterIn.PATH) @PathVariable("id") String id
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{\n" +
                            "    \"reason\": \"No longer exist\",\n" +
                            "    \"code\": \"204\",\n" +
                            "    \"@baseType\": ProductCatalog\n" +
                            "    \"@type\": \"Catalog\"\n" +
                            "    \"message\": \"The product catalog with ID '2234' has been successfully deleted.\",\n" +
                            "    \"referenceError\": \"https://openapi-generator.tech/docs/deletions/2234\",\n" +
                            "    \"@schemaLocation\": \"https://openapi-generator.tech/catalog\",\n" +
                            "    \"status\": \"success\"\n" +
                            "}";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"message\" : \"message\", \"referenceError\" : \"https://openapi-generator.tech\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"message\" : \"message\", \"referenceError\" : \"https://openapi-generator.tech\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"message\" : \"message\", \"referenceError\" : \"https://openapi-generator.tech\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"message\" : \"message\", \"referenceError\" : \"https://openapi-generator.tech\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"message\" : \"message\", \"referenceError\" : \"https://openapi-generator.tech\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"message\" : \"message\", \"referenceError\" : \"https://openapi-generator.tech\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.OK);

    }


    /**
     * GET /catalog : List or find Catalog objects
     * This operation list or find Catalog entities
     *
     * @param fields Comma-separated properties to be provided in response (optional)
     * @param offset Requested index for start of resources to be provided in response (optional)
     * @param limit Requested number of resources to be provided in response (optional)
     * @return Success (status code 200)
     *         or Bad Request (status code 400)
     *         or Unauthorized (status code 401)
     *         or Forbidden (status code 403)
     *         or Not Found (status code 404)
     *         or Method Not allowed (status code 405)
     *         or Conflict (status code 409)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "listCatalog",
        summary = "List or find Catalog objects",
        description = "This operation list or find Catalog entities",
        tags = { "catalog" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Success", content = {
                @Content(mediaType = "application/json;charset=utf-8", array = @ArraySchema(schema = @Schema(implementation = Catalog.class)))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "401", description = "Unauthorized", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "403", description = "Forbidden", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "405", description = "Method Not allowed", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "409", description = "Conflict", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/getAllCatalog",
        produces = { "application/json;charset=utf-8" }
    )
    
    default ResponseEntity<List<Catalog>> listCatalog(
        @Parameter(name = "fields", description = "Comma-separated properties to be provided in response", in = ParameterIn.QUERY) @Valid @RequestParam(value = "fields", required = false) String fields,
        @Parameter(name = "offset", description = "Requested index for start of resources to be provided in response", in = ParameterIn.QUERY) @Valid @RequestParam(value = "offset", required = false) Integer offset,
        @Parameter(name = "limit", description = "Requested number of resources to be provided in response", in = ParameterIn.QUERY) @Valid @RequestParam(value = "limit", required = false) Integer limit
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "[{\n" +
                            "    \"catalogType\": \"Enterprise Plan\",\n" +
                            "    \"lifecycleStatus\": \"Active\",\n" +
                            "    \"validFor\": {\n" +
                            "      \"startDateTime\": \"2024-01-01T00:00:00Z\",\n" +
                            "      \"endDateTime\": \"2025-01-01T00:00:00Z\"\n" +
                            "    },\n" +
                            "    \"@type\": \"Enterprise Plan\",\n" +
                            "    \"description\": \"50GB data per month for enterprise users\",\n" +
                            "    \"relatedParty\": [\n" +
                            "      {\n" +
                            "        \"role\": \"vendor\",\n" +
                            "        \"@type\": \"RelatedPartyRefOrPartyRoleRef\",\n" +
                            "        \"partyOrPartyRole\": {\n" +
                            "          \"id\": \"3426\",\n" +
                            "          \"href\": \"https://mycsp.com:8080/tmf-api/partyManagement/v5/organization/3426\",\n" +
                            "          \"name\": \"Broadly Broad Ltd\",\n" +
                            "          \"@type\": \"PartyRef\",\n" +
                            "          \"@referredType\": \"Organization\"\n" +
                            "        }\n" +
                            "      }\n" +
                            "    ],\n" +
                            "    \"version\": \"1.1\",\n" +
                            "    \"lastUpdate\": \"2024-07-18T00:00:00Z\",\n" +
                            "    \"name\": \"AT&T Enterprise Basic Data Plan\",\n" +
                            "    \"id\": \"201\",\n" +
                            "    \"href\": \"https://mycsp.com:8080/tmfapi/productCatalogManagement/v5/productOffering/201\",\n" +
                            "    \"category\": [\n" +
                            "      {\n" +
                            "        \"@referredType\": \"ProductCategoryRef\",\n" +
                            "        \"@type\": \"CategoryType\",\n" +
                            "        \"name\": \"Cloud\",\n" +
                            "        \"id\": \"201\",\n" +
                            "        \"href\": \"https://mycsp.com:8080/tmfapi/productCatalogManagement/v5/category/201\",\n" +
                            "        \"@schemaLocation\": \"https://example.com/category\",\n" +
                            "        \"version\": \"1.0\"\n" +
                            "      }\n" +
                            "    ]\n" +
                            "  },{\n" +
                            "    \"catalogType\": \"Enterprise Plan\",\n" +
                            "    \"lifecycleStatus\": \"Active\",\n" +
                            "    \"validFor\": {\n" +
                            "      \"startDateTime\": \"2024-01-01T00:00:00Z\",\n" +
                            "      \"endDateTime\": \"2025-01-01T00:00:00Z\"\n" +
                            "    },\n" +
                            "    \"@type\": \"Enterprise Plan\",\n" +
                            "    \"description\": \"Unlimited data and priority support for enterprise users\",\n" +
                            "    \"relatedParty\": [\n" +
                            "      {\n" +
                            "        \"role\": \"vendor\",\n" +
                            "        \"@type\": \"RelatedPartyRefOrPartyRoleRef\",\n" +
                            "        \"partyOrPartyRole\": {\n" +
                            "          \"id\": \"3426\",\n" +
                            "          \"href\": \"https://mycsp.com:8080/tmf-api/partyManagement/v5/organization/3426\",\n" +
                            "          \"name\": \"Broadly Broad Ltd\",\n" +
                            "          \"@type\": \"PartyRef\",\n" +
                            "          \"@referredType\": \"Organization\"\n" +
                            "        }\n" +
                            "      },\n" +
                            "      {\n" +
                            "        \"role\": \"Reviser\",\n" +
                            "        \"@type\": \"RelatedPartyRefOrPartyRoleRef\",\n" +
                            "        \"partyOrPartyRole\": {\n" +
                            "          \"id\": \"115566\",\n" +
                            "          \"href\": \"https://mycsp.com:8080/tmf-api/partyManagement/v5/individual/115566\",\n" +
                            "          \"name\": \"Roger Collins\",\n" +
                            "          \"@type\": \"PartyRef\",\n" +
                            "          \"@referredType\": \"Individual\"\n" +
                            "        }\n" +
                            "      }\n" +
                            "    ],\n" +
                            "    \"version\": \"1.1\",\n" +
                            "    \"lastUpdate\": \"2024-07-18T00:00:00Z\",\n" +
                            "    \"name\": \"AT&T Enterprise Premium Plan\",\n" +
                            "    \"id\": \"202\",\n" +
                            "    \"href\": \"https://mycsp.com:8080/tmfapi/productCatalogManagement/v5/productOffering/202\",\n" +
                            "    \"category\": [\n" +
                            "      {\n" +
                            "        \"@referredType\": \"ProductCategoryRef\",\n" +
                            "        \"@type\": \"CategoryType\",\n" +
                            "        \"name\": \"Cloud\",\n" +
                            "        \"id\": \"202\",\n" +
                            "        \"href\": \"https://mycsp.com:8080/tmfapi/productCatalogManagement/v5/category/202\",\n" +
                            "        \"@schemaLocation\": \"https://example.com/category\",\n" +
                            "        \"version\": \"1.0\"\n" +
                            "      }\n" +
                            "    ]\n" +
                            "  },{\n" +
                            "    \"catalogType\": \"Connected Cars\",\n" +
                            "    \"lifecycleStatus\": \"Active\",\n" +
                            "    \"validFor\": {\n" +
                            "      \"startDateTime\": \"2024-01-01T00:00:00Z\",\n" +
                            "      \"endDateTime\": \"2025-01-01T00:00:00Z\"\n" +
                            "    },\n" +
                            "    \"@type\": \"Connected Cars\",\n" +
                            "    \"description\": \"Unlimited data for connected car services\",\n" +
                            "    \"relatedParty\": [\n" +
                            "     \n" +
                            "      {\n" +
                            "        \"role\": \"Reviser\",\n" +
                            "        \"@type\": \"RelatedPartyRefOrPartyRoleRef\",\n" +
                            "        \"partyOrPartyRole\": {\n" +
                            "          \"id\": \"115566\",\n" +
                            "          \"href\": \"https://mycsp.com:8080/tmf-api/partyManagement/v5/individual/115567\",\n" +
                            "          \"name\": \"Collins\",\n" +
                            "          \"@type\": \"PartyRef\",\n" +
                            "          \"@referredType\": \"Individual\"\n" +
                            "        }\n" +
                            "      }\n" +
                            "    ],\n" +
                            "    \"version\": \"1.1\",\n" +
                            "    \"lastUpdate\": \"2024-07-18T00:00:00Z\",\n" +
                            "    \"name\": \"AT&T Connected Car Basic Plan\",\n" +
                            "    \"id\": \"204\",\n" +
                            "    \"href\": \"https://mycsp.com:8080/tmfapi/productCatalogManagement/v5/productOffering/203\",\n" +
                            "    \"category\": [\n" +
                            "      {\n" +
                            "        \"@referredType\": \"ProductCategoryRef\",\n" +
                            "        \"@type\": \"CategoryType\",\n" +
                            "        \"name\": \"Cloud\",\n" +
                            "        \"id\": \"204\",\n" +
                            "        \"href\": \"https://mycsp.com:8080/tmfapi/productCatalogManagement/v5/category/203\",\n" +
                            "        \"@schemaLocation\": \"https://example.com/category\",\n" +
                            "        \"version\": \"1.0\"\n" +
                            "      }\n" +
                            "    ]\n" +
                            "  },{\n" +
                            "    \"catalogType\": \"Connected Cars\",\n" +
                            "    \"lifecycleStatus\": \"Active\",\n" +
                            "    \"validFor\": {\n" +
                            "      \"startDateTime\": \"2024-01-01T00:00:00Z\",\n" +
                            "      \"endDateTime\": \"2025-01-01T00:00:00Z\"\n" +
                            "    },\n" +
                            "    \"@type\": \"Connected Cars\",\n" +
                            "    \"description\": \"50GB data per month for enterprise users\",\n" +
                            "    \"relatedParty\": [\n" +
                            "      {\n" +
                            "        \"role\": \"vendor\",\n" +
                            "        \"@type\": \"RelatedPartyRefOrPartyRoleRef\",\n" +
                            "        \"partyOrPartyRole\": {\n" +
                            "          \"id\": \"3426\",\n" +
                            "          \"href\": \"https://mycsp.com:8080/tmf-api/partyManagement/v5/organization/342\",\n" +
                            "          \"name\": \"Tech Go Ltd\",\n" +
                            "          \"@type\": \"PartyRef\",\n" +
                            "          \"@referredType\": \"Organization\"\n" +
                            "        }\n" +
                            "      }\n" +
                            "    ],\n" +
                            "    \"version\": \"1.1\",\n" +
                            "    \"lastUpdate\": \"2024-07-18T00:00:00Z\",\n" +
                            "    \"name\": \"AT&T Connected Car Premium Plan\",\n" +
                            "    \"id\": \"205\",\n" +
                            "    \"href\": \"https://mycsp.com:8080/tmfapi/productCatalogManagement/v5/productOffering/205\",\n" +
                            "    \"category\": [\n" +
                            "      {\n" +
                            "        \"@referredType\": \"ProductCategoryRef\",\n" +
                            "        \"@type\": \"CategoryType\",\n" +
                            "        \"name\": \"Cloud\",\n" +
                            "        \"id\": \"205\",\n" +
                            "        \"href\": \"https://mycsp.com:8080/tmfapi/productCatalogManagement/v5/category/205\",\n" +
                            "        \"@schemaLocation\": \"https://example.com/category\",\n" +
                            "        \"version\": \"1.0\"\n" +
                            "      }\n" +
                            "    ]\n" +
                            "  }{\n" +
                            "    \"catalogType\": \"Mobile Services\",\n" +
                            "    \"lifecycleStatus\": \"Active\",\n" +
                            "    \"validFor\": {\n" +
                            "      \"startDateTime\": \"2024-01-01T00:00:00Z\",\n" +
                            "      \"endDateTime\": \"2025-01-01T00:00:00Z\"\n" +
                            "    },\n" +
                            "    \"@type\": \"Mobile Services\",\n" +
                            "    \"description\": \"50GB data per month for enterprise users\",\n" +
                            "    \"relatedParty\": [\n" +
                            "      {\n" +
                            "        \"role\": \"Reviser\",\n" +
                            "        \"@type\": \"RelatedPartyRefOrPartyRoleRef\",\n" +
                            "        \"partyOrPartyRole\": {\n" +
                            "          \"id\": \"1155\",\n" +
                            "          \"href\": \"https://mycsp.com:8080/tmf-api/partyManagement/v5/individual/115566\",\n" +
                            "          \"name\": \"Justin\",\n" +
                            "          \"@type\": \"PartyRef\",\n" +
                            "          \"@referredType\": \"Individual\"\n" +
                            "        }\n" +
                            "      }\n" +
                            "    ],\n" +
                            "    \"version\": \"1.1\",\n" +
                            "    \"lastUpdate\": \"2024-07-18T00:00:00Z\",\n" +
                            "    \"name\": \"AT&T Mobile Standard Plan\",\n" +
                            "    \"id\": \"205\",\n" +
                            "    \"href\": \"https://mycsp.com:8080/tmfapi/productCatalogManagement/v5/productOffering/205\",\n" +
                            "    \"category\": [\n" +
                            "      {\n" +
                            "        \"@referredType\": \"ProductCategoryRef\",\n" +
                            "        \"@type\": \"CategoryType\",\n" +
                            "        \"name\": \"Cloud\",\n" +
                            "        \"id\": \"205\",\n" +
                            "        \"href\": \"https://mycsp.com:8080/tmfapi/productCatalogManagement/v5/category/205\",\n" +
                            "        \"@schemaLocation\": \"https://example.com/category\",\n" +
                            "        \"version\": \"1.0\"\n" +
                            "      }\n" +
                            "    ]\n" +
                            "  },{\n" +
                            "    \"catalogType\": \"Mobile Services\",\n" +
                            "    \"lifecycleStatus\": \"Active\",\n" +
                            "    \"validFor\": {\n" +
                            "      \"startDateTime\": \"2024-01-01T00:00:00Z\",\n" +
                            "      \"endDateTime\": \"2025-01-01T00:00:00Z\"\n" +
                            "    },\n" +
                            "    \"@type\": \"Mobile Services\",\n" +
                            "    \"description\": \"Unlimited data, minutes, and SMS\",\n" +
                            "    \"relatedParty\": [\n" +
                            "      {\n" +
                            "        \"role\": \"Reviser\",\n" +
                            "        \"@type\": \"RelatedPartyRefOrPartyRoleRef\",\n" +
                            "        \"partyOrPartyRole\": {\n" +
                            "          \"id\": \"1155\",\n" +
                            "          \"href\": \"https://mycsp.com:8080/tmf-api/partyManagement/v5/individual/1155\",\n" +
                            "          \"name\": \"Emily\",\n" +
                            "          \"@type\": \"PartyRef\",\n" +
                            "          \"@referredType\": \"Individual\"\n" +
                            "        }\n" +
                            "      }\n" +
                            "    ],\n" +
                            "    \"version\": \"1.1\",\n" +
                            "    \"lastUpdate\": \"2024-07-18T00:00:00Z\",\n" +
                            "    \"name\": \" AT&T Mobile Premium Plan\",\n" +
                            "    \"id\": \"206\",\n" +
                            "    \"href\": \"https://mycsp.com:8080/tmfapi/productCatalogManagement/v5/productOffering/206\",\n" +
                            "    \"category\": [\n" +
                            "      {\n" +
                            "        \"@referredType\": \"ProductCategoryRef\",\n" +
                            "        \"@type\": \"CategoryType\",\n" +
                            "        \"name\": \"Cloud\",\n" +
                            "        \"id\": \"207\",\n" +
                            "        \"href\": \"https://mycsp.com:8080/tmfapi/productCatalogManagement/v5/category/206\",\n" +
                            "        \"@schemaLocation\": \"https://example.com/category\",\n" +
                            "        \"version\": \"1.0\"\n" +
                            "      }\n" +
                            "    ]\n" +
                            "  },{\n" +
                            "    \"catalogType\": \"Mobile Services\",\n" +
                            "    \"lifecycleStatus\": \"Active\",\n" +
                            "    \"validFor\": {\n" +
                            "      \"startDateTime\": \"2024-01-01T00:00:00Z\",\n" +
                            "      \"endDateTime\": \"2025-01-01T00:00:00Z\"\n" +
                            "    },\n" +
                            "    \"@type\": \"Mobile Services\",\n" +
                            "    \"description\": \"10GB data, unlimited minutes and SMS per month\",\n" +
                            "    \"relatedParty\": [\n" +
                            "      {\n" +
                            "        \"role\": \"vendor\",\n" +
                            "        \"@type\": \"RelatedPartyRefOrPartyRoleRef\",\n" +
                            "        \"partyOrPartyRole\": {\n" +
                            "          \"id\": \"207\",\n" +
                            "          \"href\": \"https://mycsp.com:8080/tmf-api/partyManagement/v5/organization/207\",\n" +
                            "          \"name\": \"Broadly Broad Ltd\",\n" +
                            "          \"@type\": \"PartyRef\",\n" +
                            "          \"@referredType\": \"Organization\"\n" +
                            "        }\n" +
                            "      }\n" +
                            "    ],\n" +
                            "    \"version\": \"1.1\",\n" +
                            "    \"lastUpdate\": \"2024-07-18T00:00:00Z\",\n" +
                            "    \"name\": \"\"AT&T Mobile Standard Plan\"\",\n" +
                            "    \"id\": \"207\",\n" +
                            "    \"href\": \"https://mycsp.com:8080/tmfapi/productCatalogManagement/v5/productOffering/207\",\n" +
                            "    \"category\": [\n" +
                            "      {\n" +
                            "        \"@referredType\": \"ProductCategoryRef\",\n" +
                            "        \"@type\": \"CategoryType\",\n" +
                            "        \"name\": \"Cloud\",\n" +
                            "        \"id\": \"207\",\n" +
                            "        \"href\": \"https://mycsp.com:8080/tmfapi/productCatalogManagement/v5/category/207\",\n" +
                            "        \"@schemaLocation\": \"https://example.com/category\",\n" +
                            "        \"version\": \"1.0\"\n" +
                            "      }\n" +
                            "    ]\n" +
                            "  },{\n" +
                            "    \"catalogType\": \"Mobile Services\",\n" +
                            "    \"lifecycleStatus\": \"Active\",\n" +
                            "    \"validFor\": {\n" +
                            "      \"startDateTime\": \"2024-01-01T00:00:00Z\",\n" +
                            "      \"endDateTime\": \"2025-01-01T00:00:00Z\"\n" +
                            "    },\n" +
                            "    \"@type\": \"Mobile Services\",\n" +
                            "    \"description\": \"Unlimited voice calls for enterprise users\",\n" +
                            "    \"relatedParty\": [\n" +
                            "      {\n" +
                            "        \"role\": \"Reviser\",\n" +
                            "        \"@type\": \"RelatedPartyRefOrPartyRoleRef\",\n" +
                            "        \"partyOrPartyRole\": {\n" +
                            "          \"id\": \"208\",\n" +
                            "          \"href\": \"https://mycsp.com:8080/tmf-api/partyManagement/v5/individual/208\",\n" +
                            "          \"name\": \"Megs\",\n" +
                            "          \"@type\": \"PartyRef\",\n" +
                            "          \"@referredType\": \"Individual\"\n" +
                            "        }\n" +
                            "      }\n" +
                            "    ],\n" +
                            "    \"version\": \"1.1\",\n" +
                            "    \"lastUpdate\": \"2024-07-18T00:00:00Z\",\n" +
                            "    \"name\": \"AT&T Mobile International Plan\",\n" +
                            "    \"id\": \"208\",\n" +
                            "    \"href\": \"https://mycsp.com:8080/tmfapi/productCatalogManagement/v5/productOffering/208\",\n" +
                            "    \"category\": [\n" +
                            "      {\n" +
                            "        \"@referredType\": \"ProductCategoryRef\",\n" +
                            "        \"@type\": \"CategoryType\",\n" +
                            "        \"name\": \"Cloud\",\n" +
                            "        \"id\": \"208\",\n" +
                            "        \"href\": \"https://mycsp.com:8080/tmfapi/productCatalogManagement/v5/category/208\",\n" +
                            "        \"@schemaLocation\": \"https://example.com/category\",\n" +
                            "        \"version\": \"1.0\"\n" +
                            "      }\n" +
                            "    ]\n" +
                            "  },{\n" +
                            "    \"catalogType\": \"Enterprise Plan\",\n" +
                            "    \"lifecycleStatus\": \"Active\",\n" +
                            "    \"validFor\": {\n" +
                            "      \"startDateTime\": \"2024-01-01T00:00:00Z\",\n" +
                            "      \"endDateTime\": \"2025-01-01T00:00:00Z\"\n" +
                            "    },\n" +
                            "    \"@type\": \"Enterprise Plan\",\n" +
                            "    \"description\": \"Unlimited SMS for enterprise users\",\n" +
                            "    \"relatedParty\": [\n" +
                            "      {\n" +
                            "        \"role\": \"vendor\",\n" +
                            "        \"@type\": \"RelatedPartyRefOrPartyRoleRef\",\n" +
                            "        \"partyOrPartyRole\": {\n" +
                            "          \"id\": \"346\",\n" +
                            "          \"href\": \"https://mycsp.com:8080/tmf-api/partyManagement/v5/organization/346\",\n" +
                            "          \"name\": \"Tech Ltd\",\n" +
                            "          \"@type\": \"PartyRef\",\n" +
                            "          \"@referredType\": \"Organization\"\n" +
                            "        }\n" +
                            "      }\n" +
                            "    ],\n" +
                            "    \"version\": \"1.1\",\n" +
                            "    \"lastUpdate\": \"2024-07-18T00:00:00Z\",\n" +
                            "    \"name\": \"AT&T Enterprise SMS Plan\",\n" +
                            "    \"id\": \"210\",\n" +
                            "    \"href\": \"https://mycsp.com:8080/tmfapi/productCatalogManagement/v5/productOffering/201\",\n" +
                            "    \"category\": [\n" +
                            "      {\n" +
                            "        \"@referredType\": \"ProductCategoryRef\",\n" +
                            "        \"@type\": \"CategoryType\",\n" +
                            "        \"name\": \"Cloud\",\n" +
                            "        \"id\": \"210\",\n" +
                            "        \"href\": \"https://mycsp.com:8080/tmfapi/productCatalogManagement/v5/category/210\",\n" +
                            "        \"@schemaLocation\": \"https://example.com/category\",\n" +
                            "        \"version\": \"1.0\"\n" +
                            "      }\n" +
                            "    ]\n" +
                            "  },\n" +
                            "{\n" +
                            "    \"catalogType\": \"Connected Cars\",\n" +
                            "    \"lifecycleStatus\": \"Active\",\n" +
                            "    \"validFor\": {\n" +
                            "      \"startDateTime\": \"2024-01-01T00:00:00Z\",\n" +
                            "      \"endDateTime\": \"2025-01-01T00:00:00Z\"\n" +
                            "    },\n" +
                            "    \"@type\": \"Connected Cars\",\n" +
                            "    \"description\": \"100 minutes of voice calls for connected car services\",\n" +
                            "    \"relatedParty\": [\n" +
                            "      {\n" +
                            "        \"role\": \"vendor\",\n" +
                            "        \"@type\": \"RelatedPartyRefOrPartyRoleRef\",\n" +
                            "        \"partyOrPartyRole\": {\n" +
                            "          \"id\": \"3426\",\n" +
                            "          \"href\": \"https://mycsp.com:8080/tmf-api/partyManagement/v5/organization/3426\",\n" +
                            "          \"name\": \"ASP Ltd\",\n" +
                            "          \"@type\": \"PartyRef\",\n" +
                            "          \"@referredType\": \"Organization\"\n" +
                            "        }\n" +
                            "      }\n" +
                            "    ],\n" +
                            "    \"version\": \"1.1\",\n" +
                            "    \"lastUpdate\": \"2024-07-18T00:00:00Z\",\n" +
                            "    \"name\": \"AT&T Connected Car Voice Plan\",\n" +
                            "    \"id\": \"211\",\n" +
                            "    \"href\": \"https://mycsp.com:8080/tmfapi/productCatalogManagement/v5/productOffering/211\",\n" +
                            "    \"category\": [\n" +
                            "      {\n" +
                            "        \"@referredType\": \"ProductCategoryRef\",\n" +
                            "        \"@type\": \"CategoryType\",\n" +
                            "        \"name\": \"Cloud\",\n" +
                            "        \"id\": \"211\",\n" +
                            "        \"href\": \"https://mycsp.com:8080/tmfapi/productCatalogManagement/v5/category/211\",\n" +
                            "        \"@schemaLocation\": \"https://example.com/category\",\n" +
                            "        \"version\": \"1.0\"\n" +
                            "      }\n" +
                            "    ]\n" +
                            "  }]";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"message\" : \"message\", \"referenceError\" : \"https://openapi-generator.tech\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"message\" : \"message\", \"referenceError\" : \"https://openapi-generator.tech\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"message\" : \"message\", \"referenceError\" : \"https://openapi-generator.tech\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"message\" : \"message\", \"referenceError\" : \"https://openapi-generator.tech\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"message\" : \"message\", \"referenceError\" : \"https://openapi-generator.tech\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"message\" : \"message\", \"referenceError\" : \"https://openapi-generator.tech\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"message\" : \"message\", \"referenceError\" : \"https://openapi-generator.tech\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.FOUND);

    }


    /**
     * PATCH /catalog/{id} : Updates partially a Catalog
     * This operation updates partially a Catalog entity.
     *
     * @param id Identifier of the Catalog (required)
     * @param catalog The Catalog to be updated (required)
     * @return Updated (status code 200)
     *         or Bad Request (status code 400)
     *         or Unauthorized (status code 401)
     *         or Forbidden (status code 403)
     *         or Not Found (status code 404)
     *         or Method Not allowed (status code 405)
     *         or Conflict (status code 409)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "patchCatalog",
        summary = "Updates partially a Catalog",
        description = "This operation updates partially a Catalog entity.",
        tags = { "catalog" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Updated", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Catalog.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "401", description = "Unauthorized", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "403", description = "Forbidden", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "405", description = "Method Not allowed", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "409", description = "Conflict", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PATCH,
        value = "/updateCatalog/{id}",
        produces = { "application/json;charset=utf-8" },
        consumes = { "application/json;charset=utf-8" }
    )
    
    default ResponseEntity<Catalog> patchCatalog(
        @Parameter(name = "id", description = "Identifier of the Catalog", required = true, in = ParameterIn.PATH) @PathVariable("id") String id,
        @Parameter(name = "catalog", description = "The Catalog to be updated", required = true) @Valid @RequestBody CatalogUpdate catalog
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{\n" +
                            "    \"catalogType\": \"Product Catalog\",\n" +
                            "    \"lifecycleStatus\": \"Active\",\n" +
                            "    \"validFor\": {\n" +
                            "        \"startDateTime\": \"1985-04-12T23:20:50.52Z\",\n" +
                            "        \"endDateTime\": \"1985-04-12T23:20:50.52Z\"\n" +
                            "    },\n" +
                            "    \"@type\": \"CatalogType\",\n" +
                            "    \"description\": \"This catalog contains all available products and services.\",\n" +
                            "    \"relatedParty\": [\n" +
                            "        {\n" +
                            "            \"@referredType\": \"Organization\",\n" +
                            "            \"role\": \"Supplier\",\n" +
                            "            \"@baseType\": \"BaseType\",\n" +
                            "            \"@type\": \"RelatedPartyType\",\n" +
                            "            \"name\": \"Tech Supplies Co.\",\n" +
                            "            \"id\": \"RP101\",\n" +
                            "            \"href\": \"https://openapi-generator.tech/suppliers/tech-supplies\",\n" +
                            "            \"@schemaLocation\": \"https://openapi-generator.tech/schema\"\n" +
                            "        },\n" +
                            "        {\n" +
                            "            \"@referredType\": \"Organization\",\n" +
                            "            \"role\": \"Distributor\",\n" +
                            "            \"@baseType\": \"BaseType\",\n" +
                            "            \"@type\": \"RelatedPartyType\",\n" +
                            "            \"name\": \"Global Distributors Inc.\",\n" +
                            "            \"id\": \"RP102\",\n" +
                            "            \"href\": \"https://openapi-generator.tech/distributors/global-distributors\",\n" +
                            "            \"@schemaLocation\": \"https://openapi-generator.tech/schema\"\n" +
                            "        }\n" +
                            "    ],\n" +
                            "    \"version\": \"1.2\",\n" +
                            "    \"@baseType\": \"BaseType\",\n" +
                            "    \"lastUpdate\": \"2000-01-23T04:56:07.000+00:00\",\n" +
                            "    \"name\": \"Global Product Catalog\",\n" +
                            "    \"id\": \"C1001\",\n" +
                            "    \"href\": \"https://openapi-generator.tech/catalogs/global-product-catalog\",\n" +
                            "    \"category\": [\n" +
                            "        {\n" +
                            "            \"@referredType\": \"ProductCategoryRef\",\n" +
                            "            \"@baseType\": \"BaseType\",\n" +
                            "            \"@type\": \"CategoryType\",\n" +
                            "            \"name\": \"Electronics\",\n" +
                            "            \"id\": \"CAT101\",\n" +
                            "            \"href\": \"https://openapi-generator.tech/categories/electronics\",\n" +
                            "            \"@schemaLocation\": \"https://openapi-generator.tech/schema\",\n" +
                            "            \"version\": \"1.0\"\n" +
                            "        },\n" +
                            "        {\n" +
                            "            \"@referredType\": \"ProductCategoryRef\",\n" +
                            "            \"@baseType\": \"BaseType\",\n" +
                            "            \"@type\": \"CategoryType\",\n" +
                            "            \"name\": \"Home Appliances\",\n" +
                            "            \"id\": \"CAT102\",\n" +
                            "            \"href\": \"https://openapi-generator.tech/categories/home-appliances\",\n" +
                            "            \"@schemaLocation\": \"https://openapi-generator.tech/schema\",\n" +
                            "            \"version\": \"1.0\"\n" +
                            "        }\n" +
                            "    ],\n" +
                            "    \"@schemaLocation\": \"https://openapi-generator.tech/schema\"\n" +
                            "}\n";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"message\" : \"message\", \"referenceError\" : \"https://openapi-generator.tech\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"message\" : \"message\", \"referenceError\" : \"https://openapi-generator.tech\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"message\" : \"message\", \"referenceError\" : \"https://openapi-generator.tech\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"message\" : \"message\", \"referenceError\" : \"https://openapi-generator.tech\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"message\" : \"message\", \"referenceError\" : \"https://openapi-generator.tech\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"message\" : \"message\", \"referenceError\" : \"https://openapi-generator.tech\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"message\" : \"message\", \"referenceError\" : \"https://openapi-generator.tech\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.OK);

    }


    /**
     * GET /catalog/{id} : Retrieves a Catalog by ID
     * This operation retrieves a Catalog entity. Attribute selection is enabled for all first level attributes.
     *
     * @param id Identifier of the Catalog (required)
     * @param fields Comma-separated properties to provide in response (optional)
     * @return Success (status code 200)
     *         or Bad Request (status code 400)
     *         or Unauthorized (status code 401)
     *         or Forbidden (status code 403)
     *         or Not Found (status code 404)
     *         or Method Not allowed (status code 405)
     *         or Conflict (status code 409)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "retrieveCatalog",
        summary = "Retrieves a Catalog by ID",
        description = "This operation retrieves a Catalog entity. Attribute selection is enabled for all first level attributes.",
        tags = { "catalog" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Success", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Catalog.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "401", description = "Unauthorized", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "403", description = "Forbidden", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "405", description = "Method Not allowed", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "409", description = "Conflict", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/getCatalogById/{id}",
        produces = { "application/json;charset=utf-8" }
    )
    
    default ResponseEntity<Catalog> retrieveCatalog(
        @Parameter(name = "id", description = "Identifier of the Catalog", required = true, in = ParameterIn.PATH) @PathVariable("id") String id,
        @Parameter(name = "fields", description = "Comma-separated properties to provide in response", in = ParameterIn.QUERY) @Valid @RequestParam(value = "fields", required = false) String fields
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{\n" +
                            "    \"catalogType\": \"Product Catalog\",\n" +
                            "    \"lifecycleStatus\": \"Active\",\n" +
                            "    \"validFor\": {\n" +
                            "        \"startDateTime\": \"1985-04-12T23:20:50.52Z\",\n" +
                            "        \"endDateTime\": \"1985-04-12T23:20:50.52Z\"\n" +
                            "    },\n" +
                            "    \"@type\": \"Catalog\",\n" +
                            "    \"description\": \"This catalog contains all available products and services.\",\n" +
                            "    \"relatedParty\": [\n" +
                            "        {\n" +
                            "            \"@referredType\": \"Organization\",\n" +
                            "            \"role\": \"Supplier\",\n" +
                            "            \"@baseType\": \"BaseType\",\n" +
                            "            \"@type\": \"RelatedParty\",\n" +
                            "            \"name\": \"Tech Supplies Co.\",\n" +
                            "            \"id\": \"RP101\",\n" +
                            "            \"href\": \"https://openapi-generator.tech/suppliers/tech-supplies\",\n" +
                            "            \"@schemaLocation\": \"https://openapi-generator.tech/schema\"\n" +
                            "        },\n" +
                            "        {\n" +
                            "            \"@referredType\": \"Organization\",\n" +
                            "            \"role\": \"Distributor\",\n" +
                            "            \"@baseType\": \"BaseType\",\n" +
                            "            \"@type\": \"RelatedParty\",\n" +
                            "            \"name\": \"Global Distributors Inc.\",\n" +
                            "            \"id\": \"RP102\",\n" +
                            "            \"href\": \"https://openapi-generator.tech/distributors/global-distributors\",\n" +
                            "            \"@schemaLocation\": \"https://openapi-generator.tech/schema\"\n" +
                            "        }\n" +
                            "    ],\n" +
                            "    \"version\": \"1.0\",\n" +
                            "    \"@baseType\": \"CatalogBaseType\",\n" +
                            "    \"lastUpdate\": \"2000-01-23T04:56:07.000+00:00\",\n" +
                            "    \"name\": \"Global Product Catalog\",\n" +
                            "    \"id\": \"C1001\",\n" +
                            "    \"href\": \"https://openapi-generator.tech/catalogs/global-product-catalog\",\n" +
                            "    \"category\": [\n" +
                            "        {\n" +
                            "            \"@referredType\": \"ProductCategory\",\n" +
                            "            \"@baseType\": \"CategoryBaseType\",\n" +
                            "            \"@type\": \"Category\",\n" +
                            "            \"name\": \"Electronics\",\n" +
                            "            \"id\": \"CAT101\",\n" +
                            "            \"href\": \"https://openapi-generator.tech/categories/electronics\",\n" +
                            "            \"@schemaLocation\": \"https://openapi-generator.tech/schema\",\n" +
                            "            \"version\": \"1.0\"\n" +
                            "        },\n" +
                            "        {\n" +
                            "            \"@referredType\": \"ProductCategory\",\n" +
                            "            \"@baseType\": \"CategoryBaseType\",\n" +
                            "            \"@type\": \"Category\",\n" +
                            "            \"name\": \"Home Appliances\",\n" +
                            "            \"id\": \"CAT102\",\n" +
                            "            \"href\": \"https://openapi-generator.tech/categories/home-appliances\",\n" +
                            "            \"@schemaLocation\": \"https://openapi-generator.tech/schema\",\n" +
                            "            \"version\": \"1.0\"\n" +
                            "        }\n" +
                            "    ],\n" +
                            "    \"@schemaLocation\": \"https://openapi-generator.tech/schema\"\n" +
                            "}\n";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"message\" : \"message\", \"referenceError\" : \"https://openapi-generator.tech\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"message\" : \"message\", \"referenceError\" : \"https://openapi-generator.tech\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"message\" : \"message\", \"referenceError\" : \"https://openapi-generator.tech\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"message\" : \"message\", \"referenceError\" : \"https://openapi-generator.tech\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"message\" : \"message\", \"referenceError\" : \"https://openapi-generator.tech\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"message\" : \"message\", \"referenceError\" : \"https://openapi-generator.tech\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"message\" : \"message\", \"referenceError\" : \"https://openapi-generator.tech\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.FOUND);

    }

}
