/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.7.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.api;

import org.openapitools.model.Catalog;
import org.openapitools.model.CatalogCreate;
import org.openapitools.model.CatalogUpdate;
import org.openapitools.model.Error;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2024-07-16T16:55:02.035577+05:30[GMT+05:30]", comments = "Generator version: 7.7.0")
@Validated
 
//@Tag(name = "catalog", description = "the catalog API")
public interface CatalogApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * POST /catalog : Creates a Catalog
     * This operation creates a Catalog entity.
     *
     * @param catalog The Catalog to be created (required)
     * @return Created (status code 201)
     *         or Bad Request (status code 400)
     *         or Unauthorized (status code 401)
     *         or Forbidden (status code 403)
     *         or Method Not allowed (status code 405)
     *         or Conflict (status code 409)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "createCatalog",
        summary = "Creates a Catalog",
        description = "This operation creates a Catalog entity.",
        tags = { "catalog" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Created", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Catalog.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "401", description = "Unauthorized", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "403", description = "Forbidden", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "405", description = "Method Not allowed", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "409", description = "Conflict", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/createCatalog",
        produces = { "application/json;charset=utf-8" },
        consumes = { "application/json;charset=utf-8" }
    )
    
    default ResponseEntity<Catalog> createCatalog(
        @Parameter(name = "catalog", description = "The Catalog to be created", required = true) @Valid @RequestBody CatalogCreate catalog
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{\n" +
                            "    \"catalogType\": \"Product Catalog\",\n" +
                            "    \"lifecycleStatus\": \"Active\",\n" +
                            "    \"validFor\": {\n" +
                            "        \"startDateTime\": \"1985-04-12T23:20:50.52Z\",\n" +
                            "        \"endDateTime\": \"1985-04-12T23:20:50.52Z\"\n" +
                            "    },\n" +
                            "    \"@type\": \"CatalogType\",\n" +
                            "    \"description\": \"A comprehensive catalog of all available products.\",\n" +
                            "    \"relatedParty\": [\n" +
                            "        {\n" +
                            "            \"@referredType\": \"Organization\",\n" +
                            "            \"role\": \"Supplier\",\n" +
                            "            \"@baseType\": \"BaseType\",\n" +
                            "            \"@type\": \"RelatedPartyType\",\n" +
                            "            \"name\": \"Tech Supplies Co.\",\n" +
                            "            \"id\": \"RP101\",\n" +
                            "            \"href\": \"https://openapi-generator.tech/suppliers/tech-supplies\",\n" +
                            "            \"@schemaLocation\": \"https://openapi-generator.tech/schema\"\n" +
                            "        },\n" +
                            "        {\n" +
                            "            \"@referredType\": \"Organization\",\n" +
                            "            \"role\": \"Distributor\",\n" +
                            "            \"@baseType\": \"BaseType\",\n" +
                            "            \"@type\": \"RelatedPartyType\",\n" +
                            "            \"name\": \"Global Distributors Inc.\",\n" +
                            "            \"id\": \"RP102\",\n" +
                            "            \"href\": \"https://openapi-generator.tech/distributors/global-distributors\",\n" +
                            "            \"@schemaLocation\": \"https://openapi-generator.tech/schema\"\n" +
                            "        }\n" +
                            "    ],\n" +
                            "    \"version\": \"1.2\",\n" +
                            "    \"@baseType\": \"BaseType\",\n" +
                            "    \"lastUpdate\": \"2000-01-23T04:56:07.000+00:00\",\n" +
                            "    \"name\": \"Global Product Catalog\",\n" +
                            "    \"id\": \"C1001\",\n" +
                            "    \"href\": \"https://openapi-generator.tech/catalogs/global-product-catalog\",\n" +
                            "    \"category\": [\n" +
                            "        {\n" +
                            "            \"@referredType\": \"ProductCategoryRef\",\n" +
                            "            \"@baseType\": \"BaseType\",\n" +
                            "            \"@type\": \"CategoryType\",\n" +
                            "            \"name\": \"Electronics\",\n" +
                            "            \"id\": \"CAT101\",\n" +
                            "            \"href\": \"https://openapi-generator.tech/categories/electronics\",\n" +
                            "            \"@schemaLocation\": \"https://openapi-generator.tech/schema\",\n" +
                            "            \"version\": \"1.0\"\n" +
                            "        },\n" +
                            "        {\n" +
                            "            \"@referredType\": \"ProductCategoryRef\",\n" +
                            "            \"@baseType\": \"BaseType\",\n" +
                            "            \"@type\": \"CategoryType\",\n" +
                            "            \"name\": \"Home Appliances\",\n" +
                            "            \"id\": \"CAT102\",\n" +
                            "            \"href\": \"https://openapi-generator.tech/categories/home-appliances\",\n" +
                            "            \"@schemaLocation\": \"https://openapi-generator.tech/schema\",\n" +
                            "            \"version\": \"1.0\"\n" +
                            "        }\n" +
                            "    ],\n" +
                            "    \"@schemaLocation\": \"https://openapi-generator.tech/schema\"\n" +
                            "}\n";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"message\" : \"message\", \"referenceError\" : \"https://openapi-generator.tech\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"message\" : \"message\", \"referenceError\" : \"https://openapi-generator.tech\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"message\" : \"message\", \"referenceError\" : \"https://openapi-generator.tech\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"message\" : \"message\", \"referenceError\" : \"https://openapi-generator.tech\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"message\" : \"message\", \"referenceError\" : \"https://openapi-generator.tech\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"message\" : \"message\", \"referenceError\" : \"https://openapi-generator.tech\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.CREATED);

    }


    /**
     * DELETE /catalog/{id} : Deletes a Catalog
     * This operation deletes a Catalog entity.
     *
     * @param id Identifier of the Catalog (required)
     * @return Deleted (status code 204)
     *         or Bad Request (status code 400)
     *         or Unauthorized (status code 401)
     *         or Forbidden (status code 403)
     *         or Not Found (status code 404)
     *         or Method Not allowed (status code 405)
     *         or Conflict (status code 409)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "deleteCatalog",
        summary = "Deletes a Catalog",
        description = "This operation deletes a Catalog entity.",
        tags = { "catalog" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Deleted"),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "401", description = "Unauthorized", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "403", description = "Forbidden", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "405", description = "Method Not allowed", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "409", description = "Conflict", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/deleteCatalog/{id}",
        produces = { "application/json;charset=utf-8" }
    )
    
    default ResponseEntity<Void> deleteCatalog(
        @Parameter(name = "id", description = "Identifier of the Catalog", required = true, in = ParameterIn.PATH) @PathVariable("id") String id
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{\n" +
                            "    \"reason\": \"No longer exist\",\n" +
                            "    \"code\": \"204\",\n" +
                            "    \"@baseType\": ProductCatalog\n" +
                            "    \"@type\": \"Catalog\"\n" +
                            "    \"message\": \"The product catalog with ID '2234' has been successfully deleted.\",\n" +
                            "    \"referenceError\": \"https://openapi-generator.tech/docs/deletions/2234\",\n" +
                            "    \"@schemaLocation\": \"https://openapi-generator.tech/catalog\",\n" +
                            "    \"status\": \"success\"\n" +
                            "}";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"message\" : \"message\", \"referenceError\" : \"https://openapi-generator.tech\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"message\" : \"message\", \"referenceError\" : \"https://openapi-generator.tech\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"message\" : \"message\", \"referenceError\" : \"https://openapi-generator.tech\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"message\" : \"message\", \"referenceError\" : \"https://openapi-generator.tech\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"message\" : \"message\", \"referenceError\" : \"https://openapi-generator.tech\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"message\" : \"message\", \"referenceError\" : \"https://openapi-generator.tech\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.OK);

    }


    /**
     * GET /catalog : List or find Catalog objects
     * This operation list or find Catalog entities
     *
     * @param fields Comma-separated properties to be provided in response (optional)
     * @param offset Requested index for start of resources to be provided in response (optional)
     * @param limit Requested number of resources to be provided in response (optional)
     * @return Success (status code 200)
     *         or Bad Request (status code 400)
     *         or Unauthorized (status code 401)
     *         or Forbidden (status code 403)
     *         or Not Found (status code 404)
     *         or Method Not allowed (status code 405)
     *         or Conflict (status code 409)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "listCatalog",
        summary = "List or find Catalog objects",
        description = "This operation list or find Catalog entities",
        tags = { "catalog" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Success", content = {
                @Content(mediaType = "application/json;charset=utf-8", array = @ArraySchema(schema = @Schema(implementation = Catalog.class)))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "401", description = "Unauthorized", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "403", description = "Forbidden", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "405", description = "Method Not allowed", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "409", description = "Conflict", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/getAllCatalog",
        produces = { "application/json;charset=utf-8" }
    )
    
    default ResponseEntity<List<Catalog>> listCatalog(
        @Parameter(name = "fields", description = "Comma-separated properties to be provided in response", in = ParameterIn.QUERY) @Valid @RequestParam(value = "fields", required = false) String fields,
        @Parameter(name = "offset", description = "Requested index for start of resources to be provided in response", in = ParameterIn.QUERY) @Valid @RequestParam(value = "offset", required = false) Integer offset,
        @Parameter(name = "limit", description = "Requested number of resources to be provided in response", in = ParameterIn.QUERY) @Valid @RequestParam(value = "limit", required = false) Integer limit
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "[{\n" +
                            "    \"catalogType\": \"Product Catalog\",\n" +
                            "    \"lifecycleStatus\": \"Active\",\n" +
                            "    \"validFor\": {\n" +
                            "        \"startDateTime\": \"2024-01-01T00:00:00Z\",\n" +
                            "        \"endDateTime\": \"2025-01-01T00:00:00Z\"\n" +
                            "    },\n" +
                            "    \"@type\": \"CatalogType\",\n" +
                            "    \"description\": \"50GB data per month for enterprise users\",\n" +
                            "    \"relatedParty\": [\n" +
                            "        {\n" +
                            "            \"@referredType\": \"Organization\",\n" +
                            "            \"role\": \"Vendor\",\n" +
                            "            \"@baseType\": \"BaseType\",\n" +
                            "            \"@type\": \"RelatedPartyType\",\n" +
                            "            \"name\": \"Broadly Broad Ltd\",\n" +
                            "            \"id\": \"RP101\",\n" +
                            "            \"href\": \"https://example.com/suppliers/tech-supplies\",\n" +
                            "            \"@schemaLocation\": \"https://example.com/schema\"\n" +
                            "        },\n" +
                            "        {\n" +
                            "            \"@referredType\": \"Organization\",\n" +
                            "            \"role\": \"Distributor\",\n" +
                            "            \"@baseType\": \"BaseType\",\n" +
                            "            \"@type\": \"RelatedPartyType\",\n" +
                            "            \"name\": \"John Hebron\",\n" +
                            "            \"id\": \"RP102\",\n" +
                            "            \"href\": \"https://example.com/distributors/global-distributors\",\n" +
                            "            \"@schemaLocation\": \"https://example.com/schema\"\n" +
                            "        }\n" +
                            "    ],\n" +
                            "    \"version\": \"1.2\",\n" +
                            "    \"@baseType\": \"BaseType\",\n" +
                            "    \"lastUpdate\": \"2024-07-18T00:00:00Z\",\n" +
                            "    \"name\": \"Business Analytics\",\n" +
                            "    \"id\": \"C1001\",\n" +
                            "    \"href\": \"https://example.com/catalogs/global-product-catalog\",\n" +
                            "    \"category\": [\n" +
                            "        {\n" +
                            "            \"@referredType\": \"ProductCategoryRef\",\n" +
                            "            \"@baseType\": \"BaseType\",\n" +
                            "            \"@type\": \"CategoryType\",\n" +
                            "            \"name\": \"Electronics\",\n" +
                            "            \"id\": \"CAT101\",\n" +
                            "            \"href\": \"https://example.com/categories/electronics\",\n" +
                            "            \"@schemaLocation\": \"https://example.com/schema\",\n" +
                            "            \"version\": \"1.0\"\n" +
                            "        },\n" +
                            "        {\n" +
                            "            \"@referredType\": \"ProductCategoryRef\",\n" +
                            "            \"@baseType\": \"BaseType\",\n" +
                            "            \"@type\": \"CategoryType\",\n" +
                            "            \"name\": \"Home Appliances\",\n" +
                            "            \"id\": \"CAT102\",\n" +
                            "            \"href\": \"https://example.com/categories/home-appliances\",\n" +
                            "            \"@schemaLocation\": \"https://example.com/schema\",\n" +
                            "            \"version\": \"1.0\"\n" +
                            "        }\n" +
                            "    ],\n" +
                            "    \"@schemaLocation\": \"https://example.com/schema\"\n" +
                            "},{\n" +
                            "    \"catalogType\": \"Enterprise Plan\",\n" +
                            "    \"lifecycleStatus\": \"Active\",\n" +
                            "    \"validFor\": {\n" +
                            "        \"startDateTime\": \"2024-02-01T00:00:00Z\",\n" +
                            "        \"endDateTime\": \"2025-02-01T00:00:00Z\"\n" +
                            "    },\n" +
                            "    \"@type\": \"CatalogType\",\n" +
                            "    \"description\": \"10GB data, unlimited minutes and SMS per month\",\n" +
                            "    \"relatedParty\": [\n" +
                            "        {\n" +
                            "            \"@referredType\": \"Organization\",\n" +
                            "            \"role\": \"Distributor\",\n" +
                            "            \"@baseType\": \"BaseType\",\n" +
                            "            \"@type\": \"RelatedPartyType\",\n" +
                            "            \"name\": \"IT Solutions Provider\",\n" +
                            "            \"id\": \"RP103\",\n" +
                            "            \"href\": \"https://example.com/suppliers/it-solutions-provider\",\n" +
                            "            \"@schemaLocation\": \"https://example.com/schema\"\n" +
                            "        },\n" +
                            "        {\n" +
                            "            \"@referredType\": \"Organization\",\n" +
                            "            \"role\": \"Vendor\",\n" +
                            "            \"@baseType\": \"BaseType\",\n" +
                            "            \"@type\": \"RelatedPartyType\",\n" +
                            "            \"name\": \"Tech Solutions Distribution\",\n" +
                            "            \"id\": \"RP104\",\n" +
                            "            \"href\": \"https://example.com/distributors/tech-solutions-distribution\",\n" +
                            "            \"@schemaLocation\": \"https://example.com/schema\"\n" +
                            "        }\n" +
                            "    ],\n" +
                            "    \"version\": \"1.1\",\n" +
                            "    \"@baseType\": \"BaseType\",\n" +
                            "    \"lastUpdate\": \"2024-07-18T00:00:00Z\",\n" +
                            "    \"name\": \"Contact Center\",\n" +
                            "    \"id\": \"C1002\",\n" +
                            "    \"href\": \"https://example.com/catalogs/it-services\",\n" +
                            "    \"category\": [\n" +
                            "        {\n" +
                            "            \"@referredType\": \"ServiceCategoryRef\",\n" +
                            "            \"@baseType\": \"BaseType\",\n" +
                            "            \"@type\": \"CategoryType\",\n" +
                            "            \"name\": \"Cloud Solutions\",\n" +
                            "            \"id\": \"CAT103\",\n" +
                            "            \"href\": \"https://example.com/categories/cloud-solutions\",\n" +
                            "            \"@schemaLocation\": \"https://example.com/schema\",\n" +
                            "            \"version\": \"1.0\"\n" +
                            "        },\n" +
                            "        {\n" +
                            "            \"@referredType\": \"ServiceCategoryRef\",\n" +
                            "            \"@baseType\": \"BaseType\",\n" +
                            "            \"@type\": \"CategoryType\",\n" +
                            "            \"name\": \"Network Security\",\n" +
                            "            \"id\": \"CAT104\",\n" +
                            "            \"href\": \"https://example.com/categories/network-security\",\n" +
                            "            \"@schemaLocation\": \"https://example.com/schema\",\n" +
                            "            \"version\": \"1.0\"\n" +
                            "        }\n" +
                            "    ],\n" +
                            "    \"@schemaLocation\": \"https://example.com/schema\"\n" +
                            "},{\n" +
                            "    \"catalogType\": \"Product Catalog\",\n" +
                            "    \"lifecycleStatus\": \"Active\",\n" +
                            "    \"validFor\": {\n" +
                            "        \"startDateTime\": \"2024-03-01T00:00:00Z\",\n" +
                            "        \"endDateTime\": \"2025-03-01T00:00:00Z\"\n" +
                            "    },\n" +
                            "    \"@type\": \"CatalogType\",\n" +
                            "    \"description\": \"5GB data, 200 minutes, 200 SMS with international coverage\",\n" +
                            "    \"relatedParty\": [\n" +
                            "        {\n" +
                            "            \"@referredType\": \"Organization\",\n" +
                            "            \"role\": \"Supplier\",\n" +
                            "            \"@baseType\": \"BaseType\",\n" +
                            "            \"@type\": \"RelatedPartyType\",\n" +
                            "            \"name\": \"TechG ltd\",\n" +
                            "            \"id\": \"RP105\",\n" +
                            "            \"href\": \"https://example.com/suppliers/fashion-trends-store\",\n" +
                            "            \"@schemaLocation\": \"https://example.com/schema\"\n" +
                            "        }\n" +
                            "    ],\n" +
                            "    \"version\": \"1.0\",\n" +
                            "    \"@baseType\": \"BaseType\",\n" +
                            "    \"lastUpdate\": \"2024-07-18T00:00:00Z\",\n" +
                            "    \"name\": \"AT&T Mobile International Plan\",\n" +
                            "    \"id\": \"C1003\",\n" +
                            "    \"href\": \"https://example.com/catalogs/fashion-accessories\",\n" +
                            "    \"category\": [\n" +
                            "        {\n" +
                            "            \"@referredType\": \"ProductCategoryRef\",\n" +
                            "            \"@baseType\": \"BaseType\",\n" +
                            "            \"@type\": \"CategoryType\",\n" +
                            "            \"name\": \"Handbags\",\n" +
                            "            \"id\": \"CAT105\",\n" +
                            "            \"href\": \"https://example.com/categories/handbags\",\n" +
                            "            \"@schemaLocation\": \"https://example.com/schema\",\n" +
                            "            \"version\": \"1.0\"\n" +
                            "        },\n" +
                            "        {\n" +
                            "            \"@referredType\": \"ProductCategoryRef\",\n" +
                            "            \"@baseType\": \"BaseType\",\n" +
                            "            \"@type\": \"CategoryType\",\n" +
                            "            \"name\": \"Jewelry\",\n" +
                            "            \"id\": \"CAT106\",\n" +
                            "            \"href\": \"https://example.com/categories/jewelry\",\n" +
                            "            \"@schemaLocation\": \"https://example.com/schema\",\n" +
                            "            \"version\": \"1.0\"\n" +
                            "        }\n" +
                            "    ],\n" +
                            "    \"@schemaLocation\": \"https://example.com/schema\"\n" +
                            "},{\n" +
                            "    \"catalogType\": \"Service Catalog\",\n" +
                            "    \"lifecycleStatus\": \"Active\",\n" +
                            "    \"validFor\": {\n" +
                            "        \"startDateTime\": \"2024-04-01T00:00:00Z\",\n" +
                            "        \"endDateTime\": \"2025-04-01T00:00:00Z\"\n" +
                            "    },\n" +
                            "    \"@type\": \"CatalogType\",\n" +
                            "    \"description\": \"Customizable plan for large enterprises based on specific needs\",\n" +
                            "    \"relatedParty\": [\n" +
                            "        {\n" +
                            "            \"@referredType\": \"Organization\",\n" +
                            "            \"role\": \"Vendor\",\n" +
                            "            \"@baseType\": \"BaseType\",\n" +
                            "            \"@type\": \"RelatedPartyType\",\n" +
                            "            \"name\": \"AGS Group\",\n" +
                            "            \"id\": \"RP107\",\n" +
                            "            \"href\": \"https://example.com/suppliers/healthcare-providers\",\n" +
                            "            \"@schemaLocation\": \"https://example.com/schema\"\n" +
                            "        }\n" +
                            "    ],\n" +
                            "    \"version\": \"1.2\",\n" +
                            "    \"@baseType\": \"BaseType\",\n" +
                            "    \"lastUpdate\": \"2024-07-18T00:00:00Z\",\n" +
                            "    \"name\": \"Enterprise Custom Plan\",\n" +
                            "    \"id\": \"C1004\",\n" +
                            "    \"href\": \"https://example.com/catalogs/healthcare-services\",\n" +
                            "    \"category\": [\n" +
                            "        {\n" +
                            "            \"@referredType\": \"ServiceCategoryRef\",\n" +
                            "            \"@baseType\": \"BaseType\",\n" +
                            "            \"@type\": \"CategoryType\",\n" +
                            "            \"name\": \"Primary Care\",\n" +
                            "            \"id\": \"CAT107\",\n" +
                            "            \"href\": \"https://example.com/categories/primary-care\",\n" +
                            "            \"@schemaLocation\": \"https://example.com/schema\",\n" +
                            "            \"version\": \"1.0\"\n" +
                            "        },\n" +
                            "        {\n" +
                            "            \"@referredType\": \"ServiceCategoryRef\",\n" +
                            "            \"@baseType\": \"BaseType\",\n" +
                            "            \"@type\": \"CategoryType\",\n" +
                            "            \"name\": \"Specialty Care\",\n" +
                            "            \"id\": \"CAT108\",\n" +
                            "            \"href\": \"https://example.com/categories/specialty-care\",\n" +
                            "            \"@schemaLocation\": \"https://example.com/schema\",\n" +
                            "            \"version\": \"1.0\"\n" +
                            "        }\n" +
                            "    ],\n" +
                            "    \"@schemaLocation\": \"https://example.com/schema\"\n" +
                            "},{\n" +
                            "    \"catalogType\": \"Product Catalog\",\n" +
                            "    \"lifecycleStatus\": \"Active\",\n" +
                            "    \"validFor\": {\n" +
                            "        \"startDateTime\": \"2024-05-01T00:00:00Z\",\n" +
                            "        \"endDateTime\": \"2025-05-01T00:00:00Z\"\n" +
                            "    },\n" +
                            "    \"@type\": \"CatalogType\",\n" +
                            "    \"description\": \"Pay for data, minutes, and SMS as you use\",\n" +
                            "    \"relatedParty\": [\n" +
                            "        {\n" +
                            "            \"@referredType\": \"Individual\",\n" +
                            "            \"role\": \"Distributor\",\n" +
                            "            \"@baseType\": \"BaseType\",\n" +
                            "            \"@type\": \"RelatedPartyType\",\n" +
                            "            \"name\": \"Emily\",\n" +
                            "            \"id\": \"RP109\",\n" +
                            "            \"href\": \"https://example.com/suppliers/sports-gear\",\n" +
                            "            \"@schemaLocation\": \"https://example.com/schema\"\n" +
                            "        }\n" +
                            "    ],\n" +
                            "    \"version\": \"1.1\",\n" +
                            "    \"@baseType\": \"BaseType\",\n" +
                            "    \"lastUpdate\": \"2024-07-18T00:00:00Z\",\n" +
                            "    \"name\": \"AT&T Mobile Pay-As-You-Go Plan\",\n" +
                            "    \"id\": \"C1005\",\n" +
                            "    \"href\": \"https://example.com/catalogs/sports-equipment\",\n" +
                            "    \"category\": [\n" +
                            "        {\n" +
                            "            \"@referredType\": \"ProductCategoryRef\",\n" +
                            "            \"@baseType\": \"BaseType\",\n" +
                            "            \"@type\": \"CategoryType\",\n" +
                            "            \"name\": \"Fitness Accessories\",\n" +
                            "            \"id\": \"CAT109\",\n" +
                            "            \"href\": \"https://example.com/categories/fitness-accessories\",\n" +
                            "            \"@schemaLocation\": \"https://example.com/schema\",\n" +
                            "            \"version\": \"1.0\"\n" +
                            "        },\n" +
                            "        {\n" +
                            "            \"@referredType\": \"ProductCategoryRef\",\n" +
                            "            \"@baseType\": \"BaseType\",\n" +
                            "            \"@type\": \"CategoryType\",\n" +
                            "            \"name\": \"Team Sports\",\n" +
                            "            \"id\": \"CAT110\",\n" +
                            "            \"href\": \"https://example.com/categories/team-sports\",\n" +
                            "            \"@schemaLocation\": \"https://example.com/schema\",\n" +
                            "            \"version\": \"1.0\"\n" +
                            "        }\n" +
                            "    ],\n" +
                            "    \"@schemaLocation\": \"https://example.com/schema\"\n" +
                            "},{\n" +
                            "    \"catalogType\": \"Product Catalog\",\n" +
                            "    \"lifecycleStatus\": \"Active\",\n" +
                            "    \"validFor\": {\n" +
                            "        \"startDateTime\": \"2024-06-01T00:00:00Z\",\n" +
                            "        \"endDateTime\": \"2025-06-01T00:00:00Z\"\n" +
                            "    },\n" +
                            "    \"@type\": \"CatalogType\",\n" +
                            "    \"description\": \"15GB data for advanced connected car services\",\n" +
                            "    \"relatedParty\": [\n" +
                            "        {\n" +
                            "            \"@referredType\": \"Organization\",\n" +
                            "            \"role\": \"Distributor\",\n" +
                            "            \"@baseType\": \"BaseType\",\n" +
                            "            \"@type\": \"RelatedPartyType\",\n" +
                            "            \"name\": \"Pro Ltd\",\n" +
                            "            \"id\": \"RP111\",\n" +
                            "            \"href\": \"https://example.com/suppliers/bookworm-publications\",\n" +
                            "            \"@schemaLocation\": \"https://example.com/schema\"\n" +
                            "        }\n" +
                            "    ],\n" +
                            "    \"version\": \"1.0\",\n" +
                            "    \"@baseType\": \"BaseType\",\n" +
                            "    \"lastUpdate\": \"2024-07-18T00:00:00Z\",\n" +
                            "    \"name\": \"AT&T Connected Car Data Plan\",\n" +
                            "    \"id\": \"C1006\",\n" +
                            "    \"href\": \"https://example.com/catalogs/books\",\n" +
                            "    \"category\": [\n" +
                            "        {\n" +
                            "            \"@referredType\": \"ProductCategoryRef\",\n" +
                            "            \"@baseType\": \"BaseType\",\n" +
                            "            \"@type\": \"CategoryType\",\n" +
                            "            \"name\": \"Fiction\",\n" +
                            "            \"id\": \"CAT111\",\n" +
                            "            \"href\": \"https://example.com/categories/fiction\",\n" +
                            "            \"@schemaLocation\": \"https://example.com/schema\",\n" +
                            "            \"version\": \"1.0\"\n" +
                            "        },\n" +
                            "        {\n" +
                            "            \"@referredType\": \"ProductCategoryRef\",\n" +
                            "            \"@baseType\": \"BaseType\",\n" +
                            "            \"@type\": \"CategoryType\",\n" +
                            "            \"name\": \"Non-fiction\",\n" +
                            "            \"id\": \"CAT112\",\n" +
                            "            \"href\": \"https://example.com/categories/non-fiction\",\n" +
                            "            \"@schemaLocation\": \"https://example.com/schema\",\n" +
                            "            \"version\": \"1.0\"\n" +
                            "        }\n" +
                            "    ],\n" +
                            "    \"@schemaLocation\": \"https://example.com/schema\"\n" +
                            "},\n" +
                            "{\n" +
                            "    \"catalogType\": \"Service Catalog\",\n" +
                            "    \"lifecycleStatus\": \"Active\",\n" +
                            "    \"validFor\": {\n" +
                            "        \"startDateTime\": \"2024-07-01T00:00:00Z\",\n" +
                            "        \"endDateTime\": \"2025-07-01T00:00:00Z\"\n" +
                            "    },\n" +
                            "    \"@type\": \"CatalogType\",\n" +
                            "    \"description\": \"100GB data for IoT devices in enterprise settings\",\n" +
                            "    \"relatedParty\": [\n" +
                            "        {\n" +
                            "            \"@referredType\": \"Organization\",\n" +
                            "            \"role\": \"Supplier\",\n" +
                            "            \"@baseType\": \"BaseType\",\n" +
                            "            \"@type\": \"RelatedPartyType\",\n" +
                            "            \"name\": \"FDH Solutions Group\",\n" +
                            "            \"id\": \"RP113\",\n" +
                            "            \"href\": \"https://example.com/suppliers/financial-solutions-group\",\n" +
                            "            \"@schemaLocation\": \"https://example.com/schema\"\n" +
                            "        }\n" +
                            "    ],\n" +
                            "    \"version\": \"1.1\",\n" +
                            "    \"@baseType\": \"BaseType\",\n" +
                            "    \"lastUpdate\": \"2024-07-18T00:00:00Z\",\n" +
                            "    \"name\": \"AT&T Enterprise IoT Plan\",\n" +
                            "    \"id\": \"C1007\",\n" +
                            "    \"href\": \"https://example.com/catalogs/financial-services\",\n" +
                            "    \"category\": [\n" +
                            "        {\n" +
                            "            \"@referredType\": \"ServiceCategoryRef\",\n" +
                            "            \"@baseType\": \"BaseType\",\n" +
                            "            \"@type\": \"CategoryType\",\n" +
                            "            \"name\": \"Investment Services\",\n" +
                            "            \"id\": \"CAT113\",\n" +
                            "            \"href\": \"https://example.com/categories/investment-services\",\n" +
                            "            \"@schemaLocation\": \"https://example.com/schema\",\n" +
                            "            \"version\": \"1.0\"\n" +
                            "        },\n" +
                            "        {\n" +
                            "            \"@referredType\": \"ServiceCategoryRef\",\n" +
                            "            \"@baseType\": \"BaseType\",\n" +
                            "            \"@type\": \"CategoryType\",\n" +
                            "            \"name\": \"Insurance Services\",\n" +
                            "            \"id\": \"CAT114\",\n" +
                            "            \"href\": \"https://example.com/categories/insurance-services\",\n" +
                            "            \"@schemaLocation\": \"https://example.com/schema\",\n" +
                            "            \"version\": \"1.0\"\n" +
                            "        }\n" +
                            "    ],\n" +
                            "    \"@schemaLocation\": \"https://example.com/schema\"\n" +
                            "},{\n" +
                            "    \"catalogType\": \"Product Catalog\",\n" +
                            "    \"lifecycleStatus\": \"Active\",\n" +
                            "    \"validFor\": {\n" +
                            "        \"startDateTime\": \"2024-08-01T00:00:00Z\",\n" +
                            "        \"endDateTime\": \"2025-08-01T00:00:00Z\"\n" +
                            "    },\n" +
                            "    \"@type\": \"CatalogType\",\n" +
                            "    \"description\": \"5GB data, unlimited minutes and SMS for students\",\n" +
                            "    \"relatedParty\": [\n" +
                            "        {\n" +
                            "            \"@referredType\": \"Individual\",\n" +
                            "            \"role\": \"Supplier\",\n" +
                            "            \"@baseType\": \"BaseType\",\n" +
                            "            \"@type\": \"RelatedPartyType\",\n" +
                            "            \"name\": \"Daniel Nison\",\n" +
                            "            \"id\": \"RP115\",\n" +
                            "            \"href\": \"https://example.com/suppliers/green-thumb-supplies\",\n" +
                            "            \"@schemaLocation\": \"https://example.com/schema\"\n" +
                            "        }\n" +
                            "    ],\n" +
                            "    \"version\": \"1.0\",\n" +
                            "    \"@baseType\": \"BaseType\",\n" +
                            "    \"lastUpdate\": \"2024-07-18T00:00:00Z\",\n" +
                            "    \"name\": \"AT&T Mobile Student Plan\",\n" +
                            "    \"id\": \"C1008\",\n" +
                            "    \"href\": \"https://example.com/catalogs/gardening-tools\",\n" +
                            "    \"category\": [\n" +
                            "        {\n" +
                            "            \"@referredType\": \"ProductCategoryRef\",\n" +
                            "            \"@baseType\": \"BaseType\",\n" +
                            "            \"@type\": \"CategoryType\",\n" +
                            "            \"name\": \"Hand Tools\",\n" +
                            "            \"id\": \"CAT115\",\n" +
                            "            \"href\": \"https://example.com/categories/hand-tools\",\n" +
                            "            \"@schemaLocation\": \"https://example.com/schema\",\n" +
                            "            \"version\": \"1.0\"\n" +
                            "        },\n" +
                            "        {\n" +
                            "            \"@referredType\": \"ProductCategoryRef\",\n" +
                            "            \"@baseType\": \"BaseType\",\n" +
                            "            \"@type\": \"CategoryType\",\n" +
                            "            \"name\": \"Plant Care\",\n" +
                            "            \"id\": \"CAT116\",\n" +
                            "            \"href\": \"https://example.com/categories/plant-care\",\n" +
                            "            \"@schemaLocation\": \"https://example.com/schema\",\n" +
                            "            \"version\": \"1.0\"\n" +
                            "        }\n" +
                            "    ],\n" +
                            "    \"@schemaLocation\": \"https://example.com/schema\"\n" +
                            "},{\n" +
                            "    \"catalogType\": \"Service Catalog\",\n" +
                            "    \"lifecycleStatus\": \"Active\",\n" +
                            "    \"validFor\": {\n" +
                            "        \"startDateTime\": \"2024-09-01T00:00:00Z\",\n" +
                            "        \"endDateTime\": \"2025-09-01T00:00:00Z\"\n" +
                            "    },\n" +
                            "    \"@type\": \"CatalogType\",\n" +
                            "    \"description\": \"10GB shared data for multiple connected cars\",\n" +
                            "    \"relatedParty\": [\n" +
                            "        {\n" +
                            "            \"@referredType\": \"Organization\",\n" +
                            "            \"role\": \"Vendor\",\n" +
                            "            \"@baseType\": \"BaseType\",\n" +
                            "            \"@type\": \"RelatedPartyType\",\n" +
                            "            \"name\": \"Greens Ltd\",\n" +
                            "            \"id\": \"RP117\",\n" +
                            "            \"href\": \"https://example.com/suppliers/legal-solutions-firm\",\n" +
                            "            \"@schemaLocation\": \"https://example.com/schema\"\n" +
                            "        }\n" +
                            "    ],\n" +
                            "    \"version\": \"1.1\",\n" +
                            "    \"@baseType\": \"BaseType\",\n" +
                            "    \"lastUpdate\": \"2024-07-18T00:00:00Z\",\n" +
                            "    \"name\": \"AT&T Connected Car Family Plan\",\n" +
                            "    \"id\": \"C1009\",\n" +
                            "    \"href\": \"https://example.com/catalogs/legal-services\",\n" +
                            "    \"category\": [\n" +
                            "        {\n" +
                            "            \"@referredType\": \"ServiceCategoryRef\",\n" +
                            "            \"@baseType\": \"BaseType\",\n" +
                            "            \"@type\": \"CategoryType\",\n" +
                            "            \"name\": \"Corporate Law\",\n" +
                            "            \"id\": \"CAT117\",\n" +
                            "            \"href\": \"https://example.com/categories/corporate-law\",\n" +
                            "            \"@schemaLocation\": \"https://example.com/schema\",\n" +
                            "            \"version\": \"1.0\"\n" +
                            "        },\n" +
                            "        {\n" +
                            "            \"@referredType\": \"ServiceCategoryRef\",\n" +
                            "            \"@baseType\": \"BaseType\",\n" +
                            "            \"@type\": \"CategoryType\",\n" +
                            "            \"name\": \"Family Law\",\n" +
                            "            \"id\": \"CAT118\",\n" +
                            "            \"href\": \"https://example.com/categories/family-law\",\n" +
                            "            \"@schemaLocation\": \"https://example.com/schema\",\n" +
                            "            \"version\": \"1.0\"\n" +
                            "        }\n" +
                            "    ],\n" +
                            "    \"@schemaLocation\": \"https://example.com/schema\"\n" +
                            "},{\n" +
                            "    \"catalogType\": \"Product Catalog\",\n" +
                            "    \"lifecycleStatus\": \"Active\",\n" +
                            "    \"validFor\": {\n" +
                            "        \"startDateTime\": \"2024-10-01T00:00:00Z\",\n" +
                            "        \"endDateTime\": \"2025-10-01T00:00:00Z\"\n" +
                            "    },\n" +
                            "    \"@type\": \"CatalogType\",\n" +
                            "    \"description\": \"Unlimited data, minutes, and SMS with global coverage\",\n" +
                            "    \"relatedParty\": [\n" +
                            "        {\n" +
                            "            \"@referredType\": \"Organization\",\n" +
                            "            \"role\": \"Distributor\",\n" +
                            "            \"@baseType\": \"BaseType\",\n" +
                            "            \"@type\": \"RelatedPartyType\",\n" +
                            "            \"name\": \"AR Ltd\",\n" +
                            "            \"id\": \"RP120\",\n" +
                            "            \"href\": \"https://example.com/distributors/pet-supplies-distribution\",\n" +
                            "            \"@schemaLocation\": \"https://example.com/schema\"\n" +
                            "        }\n" +
                            "    ],\n" +
                            "    \"version\": \"1.0\",\n" +
                            "    \"@baseType\": \"BaseType\",\n" +
                            "    \"lastUpdate\": \"2024-07-18T00:00:00Z\",\n" +
                            "    \"name\": \"AT&T Enterprise Global Plan\",\n" +
                            "    \"id\": \"C1010\",\n" +
                            "    \"href\": \"https://example.com/catalogs/pet-supplies\",\n" +
                            "    \"category\": [\n" +
                            "        {\n" +
                            "            \"@referredType\": \"ProductCategoryRef\",\n" +
                            "            \"@baseType\": \"BaseType\",\n" +
                            "            \"@type\": \"CategoryType\",\n" +
                            "            \"name\": \"Dog Supplies\",\n" +
                            "            \"id\": \"CAT119\",\n" +
                            "            \"href\": \"https://example.com/categories/dog-supplies\",\n" +
                            "            \"@schemaLocation\": \"https://example.com/schema\",\n" +
                            "            \"version\": \"1.0\"\n" +
                            "        },\n" +
                            "        {\n" +
                            "            \"@referredType\": \"ProductCategoryRef\",\n" +
                            "            \"@baseType\": \"BaseType\",\n" +
                            "            \"@type\": \"CategoryType\",\n" +
                            "            \"name\": \"Cat Supplies\",\n" +
                            "            \"id\": \"CAT120\",\n" +
                            "            \"href\": \"https://example.com/categories/cat-supplies\",\n" +
                            "            \"@schemaLocation\": \"https://example.com/schema\",\n" +
                            "            \"version\": \"1.0\"\n" +
                            "        }\n" +
                            "    ],\n" +
                            "    \"@schemaLocation\": \"https://example.com/schema\"\n" +
                            "},{\n" +
                            "    \"catalogType\": \"Service Catalog\",\n" +
                            "    \"lifecycleStatus\": \"Active\",\n" +
                            "    \"validFor\": {\n" +
                            "        \"startDateTime\": \"2024-11-01T00:00:00Z\",\n" +
                            "        \"endDateTime\": \"2025-11-01T00:00:00Z\"\n" +
                            "    },\n" +
                            "    \"@type\": \"CatalogType\",\n" +
                            "    \"description\": \"20GB shared data, unlimited minutes and SMS for up to 5 family members\",\n" +
                            "    \"relatedParty\": [\n" +
                            "        {\n" +
                            "            \"@referredType\": \"Organization\",\n" +
                            "            \"role\": \"Vendor\",\n" +
                            "            \"@baseType\": \"BaseType\",\n" +
                            "            \"@type\": \"RelatedPartyType\",\n" +
                            "            \"name\": \"ADT Group\",\n" +
                            "            \"id\": \"RP121\",\n" +
                            "            \"href\": \"https://example.com/suppliers/travel-experts-group\",\n" +
                            "            \"@schemaLocation\": \"https://example.com/schema\"\n" +
                            "        }\n" +
                            "    ],\n" +
                            "    \"version\": \"1.1\",\n" +
                            "    \"@baseType\": \"BaseType\",\n" +
                            "    \"lastUpdate\": \"2024-07-18T00:00:00Z\",\n" +
                            "    \"name\": \"AT&T Mobile Family Plan\",\n" +
                            "    \"id\": \"C1011\",\n" +
                            "    \"href\": \"https://example.com/catalogs/travel-services\",\n" +
                            "    \"category\": [\n" +
                            "        {\n" +
                            "            \"@referredType\": \"ServiceCategoryRef\",\n" +
                            "            \"@baseType\": \"BaseType\",\n" +
                            "            \"@type\": \"CategoryType\",\n" +
                            "            \"name\": \"Flight Booking\",\n" +
                            "            \"id\": \"CAT121\",\n" +
                            "            \"href\": \"https://example.com/categories/flight-booking\",\n" +
                            "            \"@schemaLocation\": \"https://example.com/schema\",\n" +
                            "            \"version\": \"1.0\"\n" +
                            "        },\n" +
                            "        {\n" +
                            "            \"@referredType\": \"ServiceCategoryRef\",\n" +
                            "            \"@baseType\": \"BaseType\",\n" +
                            "            \"@type\": \"CategoryType\",\n" +
                            "            \"name\": \"Hotel Reservations\",\n" +
                            "            \"id\": \"CAT122\",\n" +
                            "            \"href\": \"https://example.com/categories/hotel-reservations\",\n" +
                            "            \"@schemaLocation\": \"https://example.com/schema\",\n" +
                            "            \"version\": \"1.0\"\n" +
                            "        }\n" +
                            "    ],\n" +
                            "    \"@schemaLocation\": \"https://example.com/schema\"\n" +
                            "},{\n" +
                            "    \"catalogType\": \"Product Catalog\",\n" +
                            "    \"lifecycleStatus\": \"Active\",\n" +
                            "    \"validFor\": {\n" +
                            "        \"startDateTime\": \"2024-12-01T00:00:00Z\",\n" +
                            "        \"endDateTime\": \"2025-12-01T00:00:00Z\"\n" +
                            "    },\n" +
                            "    \"@type\": \"CatalogType\",\n" +
                            "    \"description\": \"100 minutes of voice calls for connected car services\",\n" +
                            "    \"relatedParty\": [\n" +
                            "        {\n" +
                            "            \"@referredType\": \"Organization\",\n" +
                            "            \"role\": \"Distributor\",\n" +
                            "            \"@baseType\": \"BaseType\",\n" +
                            "            \"@type\": \"RelatedPartyType\",\n" +
                            "            \"name\": \"SF Ltd\",\n" +
                            "            \"id\": \"RP123\",\n" +
                            "            \"href\": \"https://example.com/suppliers/kitchen-essentials\",\n" +
                            "            \"@schemaLocation\": \"https://example.com/schema\"\n" +
                            "        }\n" +
                            "    ],\n" +
                            "    \"version\": \"1.0\",\n" +
                            "    \"@baseType\": \"BaseType\",\n" +
                            "    \"lastUpdate\": \"2024-07-18T00:00:00Z\",\n" +
                            "    \"name\": \"AT&T Connected Car Voice Plan\",\n" +
                            "    \"id\": \"C1012\",\n" +
                            "    \"href\": \"https://example.com/catalogs/kitchen-appliances\",\n" +
                            "    \"category\": [\n" +
                            "        {\n" +
                            "            \"@referredType\": \"ProductCategoryRef\",\n" +
                            "            \"@baseType\": \"BaseType\",\n" +
                            "            \"@type\": \"CategoryType\",\n" +
                            "            \"name\": \"Small Appliances\",\n" +
                            "            \"id\": \"CAT123\",\n" +
                            "            \"href\": \"https://example.com/categories/small-appliances\",\n" +
                            "            \"@schemaLocation\": \"https://example.com/schema\",\n" +
                            "            \"version\": \"1.0\"\n" +
                            "        },\n" +
                            "        {\n" +
                            "            \"@referredType\": \"ProductCategoryRef\",\n" +
                            "            \"@baseType\": \"BaseType\",\n" +
                            "            \"@type\": \"CategoryType\",\n" +
                            "            \"name\": \"Large Appliances\",\n" +
                            "            \"id\": \"CAT124\",\n" +
                            "            \"href\": \"https://example.com/categories/large-appliances\",\n" +
                            "            \"@schemaLocation\": \"https://example.com/schema\",\n" +
                            "            \"version\": \"1.0\"\n" +
                            "        }\n" +
                            "    ],\n" +
                            "    \"@schemaLocation\": \"https://example.com/schema\"\n" +
                            "}\n" +
                            "]";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"message\" : \"message\", \"referenceError\" : \"https://openapi-generator.tech\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"message\" : \"message\", \"referenceError\" : \"https://openapi-generator.tech\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"message\" : \"message\", \"referenceError\" : \"https://openapi-generator.tech\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"message\" : \"message\", \"referenceError\" : \"https://openapi-generator.tech\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"message\" : \"message\", \"referenceError\" : \"https://openapi-generator.tech\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"message\" : \"message\", \"referenceError\" : \"https://openapi-generator.tech\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"message\" : \"message\", \"referenceError\" : \"https://openapi-generator.tech\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.FOUND);

    }


    /**
     * PATCH /catalog/{id} : Updates partially a Catalog
     * This operation updates partially a Catalog entity.
     *
     * @param id Identifier of the Catalog (required)
     * @param catalog The Catalog to be updated (required)
     * @return Updated (status code 200)
     *         or Bad Request (status code 400)
     *         or Unauthorized (status code 401)
     *         or Forbidden (status code 403)
     *         or Not Found (status code 404)
     *         or Method Not allowed (status code 405)
     *         or Conflict (status code 409)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "patchCatalog",
        summary = "Updates partially a Catalog",
        description = "This operation updates partially a Catalog entity.",
        tags = { "catalog" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Updated", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Catalog.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "401", description = "Unauthorized", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "403", description = "Forbidden", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "405", description = "Method Not allowed", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "409", description = "Conflict", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PATCH,
        value = "/updateCatalog/{id}",
        produces = { "application/json;charset=utf-8" },
        consumes = { "application/json;charset=utf-8" }
    )
    
    default ResponseEntity<Catalog> patchCatalog(
        @Parameter(name = "id", description = "Identifier of the Catalog", required = true, in = ParameterIn.PATH) @PathVariable("id") String id,
        @Parameter(name = "catalog", description = "The Catalog to be updated", required = true) @Valid @RequestBody CatalogUpdate catalog
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{\n" +
                            "    \"catalogType\": \"Product Catalog\",\n" +
                            "    \"lifecycleStatus\": \"Active\",\n" +
                            "    \"validFor\": {\n" +
                            "        \"startDateTime\": \"1985-04-12T23:20:50.52Z\",\n" +
                            "        \"endDateTime\": \"1985-04-12T23:20:50.52Z\"\n" +
                            "    },\n" +
                            "    \"@type\": \"CatalogType\",\n" +
                            "    \"description\": \"This catalog contains all available products and services.\",\n" +
                            "    \"relatedParty\": [\n" +
                            "        {\n" +
                            "            \"@referredType\": \"Organization\",\n" +
                            "            \"role\": \"Supplier\",\n" +
                            "            \"@baseType\": \"BaseType\",\n" +
                            "            \"@type\": \"RelatedPartyType\",\n" +
                            "            \"name\": \"Tech Supplies Co.\",\n" +
                            "            \"id\": \"RP101\",\n" +
                            "            \"href\": \"https://openapi-generator.tech/suppliers/tech-supplies\",\n" +
                            "            \"@schemaLocation\": \"https://openapi-generator.tech/schema\"\n" +
                            "        },\n" +
                            "        {\n" +
                            "            \"@referredType\": \"Organization\",\n" +
                            "            \"role\": \"Distributor\",\n" +
                            "            \"@baseType\": \"BaseType\",\n" +
                            "            \"@type\": \"RelatedPartyType\",\n" +
                            "            \"name\": \"Global Distributors Inc.\",\n" +
                            "            \"id\": \"RP102\",\n" +
                            "            \"href\": \"https://openapi-generator.tech/distributors/global-distributors\",\n" +
                            "            \"@schemaLocation\": \"https://openapi-generator.tech/schema\"\n" +
                            "        }\n" +
                            "    ],\n" +
                            "    \"version\": \"1.2\",\n" +
                            "    \"@baseType\": \"BaseType\",\n" +
                            "    \"lastUpdate\": \"2000-01-23T04:56:07.000+00:00\",\n" +
                            "    \"name\": \"Global Product Catalog\",\n" +
                            "    \"id\": \"C1001\",\n" +
                            "    \"href\": \"https://openapi-generator.tech/catalogs/global-product-catalog\",\n" +
                            "    \"category\": [\n" +
                            "        {\n" +
                            "            \"@referredType\": \"ProductCategoryRef\",\n" +
                            "            \"@baseType\": \"BaseType\",\n" +
                            "            \"@type\": \"CategoryType\",\n" +
                            "            \"name\": \"Electronics\",\n" +
                            "            \"id\": \"CAT101\",\n" +
                            "            \"href\": \"https://openapi-generator.tech/categories/electronics\",\n" +
                            "            \"@schemaLocation\": \"https://openapi-generator.tech/schema\",\n" +
                            "            \"version\": \"1.0\"\n" +
                            "        },\n" +
                            "        {\n" +
                            "            \"@referredType\": \"ProductCategoryRef\",\n" +
                            "            \"@baseType\": \"BaseType\",\n" +
                            "            \"@type\": \"CategoryType\",\n" +
                            "            \"name\": \"Home Appliances\",\n" +
                            "            \"id\": \"CAT102\",\n" +
                            "            \"href\": \"https://openapi-generator.tech/categories/home-appliances\",\n" +
                            "            \"@schemaLocation\": \"https://openapi-generator.tech/schema\",\n" +
                            "            \"version\": \"1.0\"\n" +
                            "        }\n" +
                            "    ],\n" +
                            "    \"@schemaLocation\": \"https://openapi-generator.tech/schema\"\n" +
                            "}\n";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"message\" : \"message\", \"referenceError\" : \"https://openapi-generator.tech\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"message\" : \"message\", \"referenceError\" : \"https://openapi-generator.tech\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"message\" : \"message\", \"referenceError\" : \"https://openapi-generator.tech\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"message\" : \"message\", \"referenceError\" : \"https://openapi-generator.tech\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"message\" : \"message\", \"referenceError\" : \"https://openapi-generator.tech\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"message\" : \"message\", \"referenceError\" : \"https://openapi-generator.tech\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"message\" : \"message\", \"referenceError\" : \"https://openapi-generator.tech\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.OK);

    }


    /**
     * GET /catalog/{id} : Retrieves a Catalog by ID
     * This operation retrieves a Catalog entity. Attribute selection is enabled for all first level attributes.
     *
     * @param id Identifier of the Catalog (required)
     * @param fields Comma-separated properties to provide in response (optional)
     * @return Success (status code 200)
     *         or Bad Request (status code 400)
     *         or Unauthorized (status code 401)
     *         or Forbidden (status code 403)
     *         or Not Found (status code 404)
     *         or Method Not allowed (status code 405)
     *         or Conflict (status code 409)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "retrieveCatalog",
        summary = "Retrieves a Catalog by ID",
        description = "This operation retrieves a Catalog entity. Attribute selection is enabled for all first level attributes.",
        tags = { "catalog" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Success", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Catalog.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "401", description = "Unauthorized", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "403", description = "Forbidden", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "405", description = "Method Not allowed", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "409", description = "Conflict", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json;charset=utf-8", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/getCatalogById/{id}",
        produces = { "application/json;charset=utf-8" }
    )
    
    default ResponseEntity<Catalog> retrieveCatalog(
        @Parameter(name = "id", description = "Identifier of the Catalog", required = true, in = ParameterIn.PATH) @PathVariable("id") String id,
        @Parameter(name = "fields", description = "Comma-separated properties to provide in response", in = ParameterIn.QUERY) @Valid @RequestParam(value = "fields", required = false) String fields
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{\n" +
                            "    \"catalogType\": \"Product Catalog\",\n" +
                            "    \"lifecycleStatus\": \"Active\",\n" +
                            "    \"validFor\": {\n" +
                            "        \"startDateTime\": \"1985-04-12T23:20:50.52Z\",\n" +
                            "        \"endDateTime\": \"1985-04-12T23:20:50.52Z\"\n" +
                            "    },\n" +
                            "    \"@type\": \"Catalog\",\n" +
                            "    \"description\": \"This catalog contains all available products and services.\",\n" +
                            "    \"relatedParty\": [\n" +
                            "        {\n" +
                            "            \"@referredType\": \"Organization\",\n" +
                            "            \"role\": \"Supplier\",\n" +
                            "            \"@baseType\": \"BaseType\",\n" +
                            "            \"@type\": \"RelatedParty\",\n" +
                            "            \"name\": \"Tech Supplies Co.\",\n" +
                            "            \"id\": \"RP101\",\n" +
                            "            \"href\": \"https://openapi-generator.tech/suppliers/tech-supplies\",\n" +
                            "            \"@schemaLocation\": \"https://openapi-generator.tech/schema\"\n" +
                            "        },\n" +
                            "        {\n" +
                            "            \"@referredType\": \"Organization\",\n" +
                            "            \"role\": \"Distributor\",\n" +
                            "            \"@baseType\": \"BaseType\",\n" +
                            "            \"@type\": \"RelatedParty\",\n" +
                            "            \"name\": \"Global Distributors Inc.\",\n" +
                            "            \"id\": \"RP102\",\n" +
                            "            \"href\": \"https://openapi-generator.tech/distributors/global-distributors\",\n" +
                            "            \"@schemaLocation\": \"https://openapi-generator.tech/schema\"\n" +
                            "        }\n" +
                            "    ],\n" +
                            "    \"version\": \"1.0\",\n" +
                            "    \"@baseType\": \"CatalogBaseType\",\n" +
                            "    \"lastUpdate\": \"2000-01-23T04:56:07.000+00:00\",\n" +
                            "    \"name\": \"Global Product Catalog\",\n" +
                            "    \"id\": \"C1001\",\n" +
                            "    \"href\": \"https://openapi-generator.tech/catalogs/global-product-catalog\",\n" +
                            "    \"category\": [\n" +
                            "        {\n" +
                            "            \"@referredType\": \"ProductCategory\",\n" +
                            "            \"@baseType\": \"CategoryBaseType\",\n" +
                            "            \"@type\": \"Category\",\n" +
                            "            \"name\": \"Electronics\",\n" +
                            "            \"id\": \"CAT101\",\n" +
                            "            \"href\": \"https://openapi-generator.tech/categories/electronics\",\n" +
                            "            \"@schemaLocation\": \"https://openapi-generator.tech/schema\",\n" +
                            "            \"version\": \"1.0\"\n" +
                            "        },\n" +
                            "        {\n" +
                            "            \"@referredType\": \"ProductCategory\",\n" +
                            "            \"@baseType\": \"CategoryBaseType\",\n" +
                            "            \"@type\": \"Category\",\n" +
                            "            \"name\": \"Home Appliances\",\n" +
                            "            \"id\": \"CAT102\",\n" +
                            "            \"href\": \"https://openapi-generator.tech/categories/home-appliances\",\n" +
                            "            \"@schemaLocation\": \"https://openapi-generator.tech/schema\",\n" +
                            "            \"version\": \"1.0\"\n" +
                            "        }\n" +
                            "    ],\n" +
                            "    \"@schemaLocation\": \"https://openapi-generator.tech/schema\"\n" +
                            "}\n";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"message\" : \"message\", \"referenceError\" : \"https://openapi-generator.tech\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"message\" : \"message\", \"referenceError\" : \"https://openapi-generator.tech\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"message\" : \"message\", \"referenceError\" : \"https://openapi-generator.tech\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"message\" : \"message\", \"referenceError\" : \"https://openapi-generator.tech\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"message\" : \"message\", \"referenceError\" : \"https://openapi-generator.tech\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"message\" : \"message\", \"referenceError\" : \"https://openapi-generator.tech\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json;charset=utf-8"))) {
                    String exampleString = "{ \"reason\" : \"reason\", \"code\" : \"code\", \"@baseType\" : \"@baseType\", \"@type\" : \"@type\", \"message\" : \"message\", \"referenceError\" : \"https://openapi-generator.tech\", \"@schemaLocation\" : \"https://openapi-generator.tech\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json;charset=utf-8", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.FOUND);

    }

}
